"""Create user and call tables

Revision ID: f781254a82dc
Revises: 
Create Date: 2025-09-25 14:05:04.918968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f781254a82dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('source_number', sa.String(), nullable=True),
    sa.Column('destination_number', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('call_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_call_time_range', 'calls', ['start_time', 'end_time'], unique=False)
    op.create_index(op.f('ix_calls_destination_number'), 'calls', ['destination_number'], unique=False)
    op.create_index(op.f('ix_calls_external_id'), 'calls', ['external_id'], unique=True)
    op.create_index(op.f('ix_calls_source_number'), 'calls', ['source_number'], unique=False)
    op.create_index(op.f('ix_calls_start_time'), 'calls', ['start_time'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_calls_start_time'), table_name='calls')
    op.drop_index(op.f('ix_calls_source_number'), table_name='calls')
    op.drop_index(op.f('ix_calls_external_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_destination_number'), table_name='calls')
    op.drop_index('ix_call_time_range', table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###
